project:
  type: website
  output-dir: docs

website:
  title: "MLOps with vetiver"
  open-graph: true
  twitter-card: true
  site-url: https://vetiver.dev
  repo-url: https://github.com/tidymodels/vetiver.dev
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){width=65px}](https://www.rstudio.com)
    center:
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
    right:
      - icon: github
        href: https://github.com/tidymodels/vetiver
      - icon: github
        href: https://github.com/isabelizimm/vetiver-python

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: python/index.qmd
        text: Python

  sidebar:
    - id: python
      title: "python"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
      - python/index.qmd
      - href: python/get-started.ipynb
        text: Get started in python
      - href: python/vetiver-model.qmd
        text: VetiverModel
      - href: python/vetiver-api.ipynb
        text: VetiverAPI
      - href: python/examples.qmd
        text: Examples

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

