project:
  type: website
  output-dir: docs

website:
  title: "MLOps with vetiver"
  description: "Version, share, deploy, and monitor your R and Python models"
  open-graph: true
  twitter-card: true
  site-url: https://vetiver.rstudio.com
  repo-url: https://github.com/rstudio/vetiver.rstudio.com
  repo-actions: [edit, issue]
  page-navigation: true
  favicon: "images/favicon.ico"
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)
    center:
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/rstudio/vetiver.rstudio.com
        aria-label: Vetiver site GitHub

  navbar:
    background: primary
    pinned: true
    logo: "images/logo_small.png"
    left:
      - href: index.qmd
        text: Home
      - text: Get Started
        href: get-started/index.qmd
      - text: Learn More
        menu:
          - href: learn-more/parity-checklist.qmd
            text: "Function parity for R and python"
          - href: learn-more/model-card.qmd
            text: "Model cards for transparent, responsible reporting"
      - href: https://rstudio.github.io/vetiver-r/reference/
        text: R Function Reference
      - href: https://rstudio.github.io/vetiver-python/
        text: Python Function Reference

  sidebar:
    - id: get-started
      title: Get Started
      collapse-level: 2
      style: "floating"
      align: left
      contents:
        - href: get-started/index.qmd
        - href: get-started/version.qmd
        - href: get-started/deploy.qmd
        - href: get-started/monitor.qmd

    - id: learn-more
      title: Learn More
      collapse-level: 3
      align: left
      contents:
        - href: learn-more/parity-checklist.qmd
        - href: learn-more/model-card.qmd

filters:
  - grouped-tabsets

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
